### ISSUE TITLE
Create a critical alert for pods in `CrashLoopBackOff`

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1089]
When all the pods of a deployment or statefulset or daemonset are in `CrashLoopBackOff` state for more than 90sec then a critical/severe alert should be triggered.

Right now the alert that is triggered is `KubeDeploymentReplicasMismatch` after waiting for **15 minutes** in my case.

```yaml
[FIRING:1] Monitoring Event Notification
Alert:  - `warning`
 Description:
 Details:
  • alertname: `KubeDeploymentReplicasMismatch`
  • cluster: `suraj-lk-cluster`
  • container: `kube-state-metrics`
  • deployment: `fail-on-purpose`
  • endpoint: `http`
  • instance: `10.2.67.10:8080`
  • job: `kube-state-metrics`
  • namespace: `default`
  • pod: `prometheus-operator-kube-state-metrics-bd8f49464-nqh9l`
  • prometheus: `monitoring/prometheus-operator-prometheus`
  • service: `prometheus-operator-kube-state-metrics`
  • severity: `warning`
```

> **NOTE**: This issue is not about creating alert when all the pods are not in `Running` state but about all the pods being in `CrashLoopBackOff` state the two things are not same. When we look for "all the pods are not in `Running`" state then we might see many false positives.

I used following config to recreate the issue:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fail-on-purpose
  name: fail-on-purpose
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fail-on-purpose
  template:
    metadata:
      labels:
        app: fail-on-purpose
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - image: surajd/fedora-networking
        name: fedora-networking
        command: ["/bin/sh"]
        args:
        - -c
        - "echo 'sleeping' && sleep $(shuf -i 1-5 -n 1) && exit 1"
```

Install a lokomotive cluster with prometheus-operator and alertmanager configured to see above in action.

**Comment by invidian** [comment]
There is also:
```
alert: KubePodCrashLooping
expr: rate(kube_pod_container_status_restarts_total{job="kube-state-metrics",namespace=~".*"}[5m]) * 60 * 5 > 0
for: 15m
labels:
  severity: warning
annotations:
  description: Pod {{ $labels.namespace }}/{{ $labels.pod }} ({{ $labels.container }}) is restarting {{ printf "%.2f" $value }} times / 5 minutes.
  runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubepodcrashlooping
  summary: Pod is crash looping.
```

but it also has 15 minutes time range.
