### ISSUE TITLE
Linkerd and Istio PSP docs

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1252]
Apps that are meshed by either of the above service mesh components need elevated permissions. So document that if a user is meshing their application they should also add following PSP config:

```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: appname
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1337
    rule: MustRunAs
  readOnlyRootFilesystem: false
  allowedCapabilities:
  - NET_ADMIN
  - NET_RAW
  - NET_BIND_SERVICE
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 10001
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: appname-psp
  namespace: appns
rules:
- apiGroups: ['policy','extensions']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames: ['appname']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: appname-psp
  namespace: appns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: appname-psp
subjects:
- kind: ServiceAccount
  name: webapp
  namespace: appns
```
