### ISSUE TITLE
Grafana fails to load with HTTPS

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1460]
If you install Grafana with following config:

```hcl
component "prometheus-operator" {
  grafana {
    ingress {
      host                       = "grafana.suraj.io"
      certmanager_cluster_issuer = "letsencrypt-production"
    }
  }
}
```

And once it is deployed if you go to https://grafana.suraj.io then Grafana fails with error as shown in the following snapshot. But it loads fine on http.

![Screenshot from 2021-04-07 17-14-27](https://user-images.githubusercontent.com/5815795/114181437-1fd61a00-995f-11eb-8f87-5d3d38ab6051.png)

---

So it turns out that Grafana is starting with `http` protocol:

```log
...
t=2021-04-09T11:23:58+0000 lvl=info msg="inserting datasource from configuration " logger=provisioning.datasources name=Prometheus uid=
t=2021-04-09T11:23:58+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
```

Even though in the grafana config has following URL mentioned in https:

```console
$ kubectl -n monitoring get cm prometheus-operator-grafana -o yaml
apiVersion: v1
data:
  grafana.ini: |-
    ...
    [server]
    root_url = https://grafana.suraj.io
kind: ConfigMap
metadata:
  name: prometheus-operator-grafana
  namespace: monitoring
```

This is because grafana mandates the users to also specify the [protocol](https://grafana.com/docs/grafana/latest/administration/configuration/#protocol) explicitly.

With `protocol = https` you also need to provide the [`cert_file`](https://grafana.com/docs/grafana/latest/administration/configuration/#cert_file) and `cert_key`. So the new config looked like this:

```console
$ kubectl -n monitoring get cm prometheus-operator-grafana -o yaml
apiVersion: v1
data:
  grafana.ini: |-
    ...
    [server]
    root_url = https://grafana.suraj.io
    protocol = https
    cert_file = /tmp/secrets/tls.crt
    cert_key = /tmp/secrets/tls.key
kind: ConfigMap
metadata:
  name: prometheus-operator-grafana
  namespace: monitoring
```

And to get those certs in that directory inside I added following to the Grafana deployment:

```yaml
        name: grafana
        volumeMounts:
        - mountPath: /tmp/secrets
          name: tls
      volumes:
      - name: tls
        secret:
          secretName: grafana.suraj.io-tls
```

This secret is generated by cert-manager when the ingress was created.

I now expect things to work fine, but liveness and readiness probes fail because they are expecting http but the server is running https:

```console
$ kubectl -n monitoring describe pod prometheus-operator-grafana-6956548fb6-llpxd
...
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
...
  Normal   Started    53m                   kubelet            Started container grafana
  Warning  Unhealthy  51m (x11 over 53m)    kubelet            Readiness probe failed: HTTP probe failed with statuscode: 400
  Warning  Unhealthy  8m5s (x123 over 52m)  kubelet            Liveness probe failed: HTTP probe failed with statuscode: 400
  Warning  BackOff    2m58s (x82 over 35m)  kubelet            Back-off restarting failed container
```

So changed the scheme in the Grafana deployment from HTTP to HTTPS

```yaml
        livenessProbe:
          failureThreshold: 10
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTPS
...
        name: grafana
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/health
            port: 3000
            scheme: HTTPS
```

Now when I visit https://grafana.suraj.io/login I get following error on the browser:

```
Client sent an HTTP request to an HTTPS server.
```

I am guessing here the client is the ingress which is sending HTTP request to the Grafana server.

I see following on the envoy side:

```log
projectcontour/envoy-q6gbw[envoy]: [2021-04-09T12:36:37.668Z] "GET /login HTTP/2" 400 - 0 48 0 0 "1.2.3.4" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36" "84243a65-90ab-4cb5-9dc1-0a51193d9d0a" "grafana.suraj.io" "10.2.125.22:3000"
projectcontour/envoy-q6gbw[envoy]: [2021-04-09T12:36:38.544Z] "GET /favicon.ico HTTP/2" 400 - 0 48 0 0 "1.2.3.4" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36" "ab56c73e-0f79-4c0a-9aea-e5394f75b794" "grafana.suraj.io" "10.2.125.22:3000"
```
