### ISSUE TITLE
Rook docs recommend using ext4 instead of xfs

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#1494]
The rook-ceph component creates volumes with `xfs` filesystem.

https://github.com/kinvolk/lokomotive/blob/cf46dd3fe321b3c2dd7c26f2ea37f13ac8d45b72/pkg/components/rook-ceph/manifests.go#L159-L161

But in the rook docs [here](https://rook.io/docs/rook/v1.6/ceph-block.html#provision-storage), it is recommended that the volumes created should have an `ext4` over `xfs` because of the potential deadlock.

```yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-ceph-block
# Change "rook-ceph" provisioner prefix to match the operator namespace if needed
provisioner: rook-ceph.rbd.csi.ceph.com
parameters:
  # Specify the filesystem type of the volume. If not specified, csi-provisioner
  # will set default as `ext4`. Note that `xfs` is not recommended due to potential deadlock
  # in hyperconverged settings where the volume is mounted on the same node as the osds.
  csi.storage.k8s.io/fstype: ext4
```
