### ISSUE TITLE
Network policies: namespaces (kube-system, etc.) should have labels

### ISSUE THREAD

**Issue by alban** [kinvolk/lokomotive#153]
Currently, namespaces in Lokomotive don't have labels:
```
$ kubectl get ns --show-labels
NAME              STATUS   AGE   LABELS
default           Active   42m   <none>
kube-node-lease   Active   42m   <none>
kube-public       Active   42m   <none>
kube-system       Active   42m   <none>
projectcontour    Active   41m   <none>
```

This makes it difficult for users to write network policies for cross-namespace communication. A common example is a network policy allowing egress traffic to coredns in the kube-system namespace.

Examples in other projects:

- In the Calico documentation, [the "Allow DNS egress traffic" section](https://docs.projectcalico.org/security/tutorials/kubernetes-policy-advanced#5-allow-dns-egress-traffic) suggests to add the `name=kube-system` label with `kubectl label namespace kube-system name=kube-system` in order to use this namespace selector in network policies:
```
    - namespaceSelector:
        matchLabels:
          name: kube-system
```

- The Gardener project uses the label `role=kube-system`: see [the network policy for the nginx controller in the kube-system namespace](https://github.com/gardener/gardener/blob/9937e6319804b71d530de2859f61a2a2975be77e/charts/seed-bootstrap/charts/elastic-kibana-curator/templates/kibana/kibana-network-policy.yaml#L17-L23)
```
    - namespaceSelector:
        matchLabels:
          role: kube-system
      podSelector:
        matchLabels:
          app: nginx-ingress
          component: controller
```
- Or this [network policy for accessing kube-dns or coredns](https://github.com/gardener/gardener/blob/9937e6319804b71d530de2859f61a2a2975be77e/charts/global-network-policies/templates/allow-to-dns.yaml#L18):
```
    - namespaceSelector:
        matchLabels:
          role: kube-system
      podSelector:
        matchExpressions:
        - {key: k8s-app, operator: In, values: [kube-dns,coredns]}
```

We should add labels for namespaces in Lokomotive in order to:
- make it easier for users to create their network policies without patching the kube-system and other namespaces.
- make it possible to add Lokomotive components with additional network policies that would handle cross-namespace communication.
- make it possible for [Inspektor Gadget's Network Policy Advisor](https://github.com/kinvolk/inspektor-gadget/blob/master/Documentation/demo-network-policy.md) to suggest more correct cross-namespace network policies. In https://github.com/kinvolk/inspektor-gadget/pull/42, I currently just assume that the "name" label exists.

**Comment by surajssd** [comment]
So which labelling scheme are you suggesting here `name=` or `role=`?

**Comment by invidian** [comment]
In some of my projects, I used the following approach:
```
apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    name: kube-system
```

However... We need a solution, which will allow to automatically apply and update such labels. Maybe `crds` directory from `Helm` would be capable of doing that.
