### ISSUE TITLE
Monitor all the serviceMonitors in the cluster

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#19]
Prometheus-operator is currently not monitoring all the ServiceMonitors. So sets the value of `serviceMonitorSelectorNilUsesHelmValues` to `false` to make sure that all `ServiceMonitors` are selected.

When the value of `serviceMonitorSelectorNilUsesHelmValues` is `true` the `Prometheus` object's field `serviceMonitorSelector` is set with following values:

```yaml
  serviceMonitorSelector:
    matchLabels:
      release: "prometheus-operator"
```

Due to this any `ServiceMonitor` object that does not have above labels, they won't be selected. For Lokomotive we would want to keep track of all `ServiceMonitors` in the cluster.

And when `serviceMonitorSelectorNilUsesHelmValues` is set to `false`, `serviceMonitorSelector` field in `Prometheus` object is empty.
