### ISSUE TITLE
monitoring etcd

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#252]
## Description

We can reach the etcd cluster from within the cluster. But to monitor etcd we need certificates to authenticate with the etcd cluster. We can use the certificates(etcd-client-ca.crt, etcd-client.crt, etcd-client.key) generated for apiserver which are available in `kube-system` namespace secret called `kube-apiserver`. But providing those certs to the prometheus operator will be counter productive to security.

Ideally we should create certs for the metrics/monitoring user and then create such user in etcd and grant is appropriate permissions.

## TODOs

- [ ] Generate certificates for a monitoring user. Get some help on how to do that from here: https://docs.projectcalico.org/reference/etcd-rbac/certificate-generation
- [ ] Create user on etcd https://etcd.io/docs/v3.4.0/op-guide/authentication/
  - This should happen after cluster installation is done. (**Note:** Lokoctl should have a post installation hooks kinda mechanism where this can hook into. But this is out of scope of this PR.)
- [ ] Grant permissions so that it can only access metrics and nothing else.
- [ ] Make the etcd user certs available in a secret that can be then consumed by prometheus operator.
  - This can only happen when prometheus-operator is installed. Because it has to be available in monitoring namespace OR in the same namespace as prometheus-operator.

```yaml
## Component scraping etcd
##
kubeEtcd:
  enabled: true

  ## If your etcd is not deployed as a pod, specify IPs it can be found on
  ##
  endpoints: []
  # - 10.141.4.22
  # - 10.141.4.23
  # - 10.141.4.24

  ## Etcd service. If using kubeEtcd.endpoints only the port and targetPort are used
  ##
  service:
    port: 2379
    targetPort: 2379
    # selector:
    #   component: etcd

  ## Configure secure access to the etcd cluster by loading a secret into prometheus and
  ## specifying security configuration below. For example, with a secret named etcd-client-cert
  ##
  ## serviceMonitor:
  ##   scheme: https
  ##   insecureSkipVerify: false
  ##   serverName: localhost
  ##   caFile: /etc/prometheus/secrets/etcd-client-cert/etcd-ca
  ##   certFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client
  ##   keyFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client-key
  ##
  serviceMonitor:
    ## Scrape interval. If not set, the Prometheus default scrape interval is used.
    ##
    interval: ""
    scheme: http
    insecureSkipVerify: false
    serverName: ""
    caFile: ""
    certFile: ""
    keyFile: ""

    ## 	metric relabel configs to apply to samples before ingestion.
    ##
    metricRelabelings: []
    # - action: keep
    #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
    #   sourceLabels: [__name__]

    # 	relabel configs to apply to samples before ingestion.
    ##
    relabelings: []
    # - sourceLabels: [__meta_kubernetes_pod_node_name]
    #   separator: ;
    #   regex: ^(.*)$
    #   targetLabel: nodename
    #   replacement: $1
    #   action: replace
```

## Possible implementations

- Manually add a secret in upstream prometheus operator and templatise the secret. This secret and changes to the values file we will have to carry forward on each update. The values of secret can be accepted from the component. But the complication here is that we don't have a way to pass values around in lokocfg or access values within it. And where does the code for cert-creation, etcd user creation lie?

- Create a component which installs the configs like secret. This allows us to run it after prometheus-operator is installed. But then creating a new component for just secret can feel like an overkill. And where does the code for cert-creation, etcd user creation lie? Do we create a application which does this within the cluster?

- Create a sub-command in lokoctl which does all of the above tasks. Like creating user, generating certs, creating secret out of it, etc. This is better option because user can run it anytime. But then this is not easy to achieve because etcd is available only inside the cluster.
