### ISSUE TITLE
host endpoint controller is granted privileged PSP

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#287]
Host endpoint controller only needs to talk to the apiserver and should not be granted `privileged` PSP. The app inside should be able to work with `restricted` PSP.

```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/podIP: 10.2.153.1/32
    cni.projectcalico.org/podIPs: 10.2.153.1/32
    kubernetes.io/psp: privileged
  creationTimestamp: "2020-04-13T07:20:58Z"
  generateName: calico-hostendpoint-controller-846c69f698-
  labels:
    app: calico-hostendpoint-controller
    pod-template-hash: 846c69f698
    manager: kubelet
    operation: Update
    time: "2020-04-13T07:22:35Z"
  name: calico-hostendpoint-controller-846c69f698-rbvbn
  namespace: kube-system
...
```
