### ISSUE TITLE
AWS: monitoring does not seem to work / be usable out of the box

### ISSUE THREAD

**Issue by schu** [kinvolk/lokomotive#350]
lokoctl version `v0.1.0-169-gef479dc9`.

I installed the following components to setup monitoring:

```
component "metrics-server" {}

component "openebs-operator" {}

component "openebs-storage-class" {}

component "contour" {}

component "prometheus-operator" {
  grafana_admin_password = var.grafana_admin_password
}

component "cert-manager" {
  email = var.cert_manager_email
}
```

While that appears to work (all pods in namespace monitoring are running), the [existing documentation](https://github.com/kinvolk/lokomotive/blob/master/docs/configuration-reference/components/prometheus-operator.md) doesn't help with how to actually make use of it.

In order to be able to access the Grafana UI, I added an `Ingress` object:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: contour
spec:
  tls:
  - secretName: monitoring.example.com-tls
    hosts:
    - monitoring.example.com
  rules:
  - host: monitoring.example.com
    http:
      paths:
      - backend:
          serviceName: prometheus-operator-grafana
          servicePort: 80
```

The default dashboards don't seem to work:

![grafana-1](https://user-images.githubusercontent.com/366468/80306818-ee078a00-87c5-11ea-9e32-77867c195c24.png)

It looks like the Prometheus server cannot be reached (pressing the "Test" button in the data source settings results in a timeout "upstream request timeout").

What I was looking for:

* Working default setup and configuration
* Documentation on how to monitor one of my services running in the cluster (the example could show how to deploy httpbin and monitor that, i.e. how to monitor `https://httpbin.mycluster.example.com`)
* Documentation on how to monitor an external service (e.g. `https://not-on-k8s.example.com`)
* Documentation on how to add a dashboard to Grafana by code (not through the UI)
* Documentation on how to e.g. confgure Grafana with a different auth provider
* Dos and don'ts maybe
