### ISSUE TITLE
Disable automatic authorization of SSH keys on Packet

### ISSUE THREAD

**Issue by johananl** [kinvolk/lokomotive#365]
At the moment, all the user SSH keys on a Packet project are being authorized on Lokomotive clustesr. This can create security problems and infexibility.

While the Packet API doesn't currently allow disabling this functionality, we can possibly work around this by disabling the agent which queries the Packet metadata endoint for the keys:

```yaml
systemd:
  units:
    - name: "coreos-metadata-sshkeys@core.service"
      enabled: false
      mask: true
```

This way only keys explicitly specified via Ignition should be authorized.

We should look more closely into the implications of such a change before moving on it though.
