### ISSUE TITLE
enable monitoring of etcd in the default prometheus-operator component

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#42]
For etcd you need to provide necessary certificates to the prometheus-operator to ensure that it can scrape metrics from these components.

### etcd

For etcd add following snippet to the values file.

```yaml
kubeEtcd:
  enabled: true
  endpoints: {{.EtcdEndpoints}}
  service:
    port: 2381
    targetPort: 2381
  serviceMonitor:
    scheme: https
    insecureSkipVerify: false
    caFile: /etc/prometheus/secrets/etcd-client-cert/etcd-ca
    certFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client
    keyFile: /etc/prometheus/secrets/etcd-client-cert/etcd-client-key
```

But to ensure this works create a secret named `etcd-client-cert` in the same namespace as prometheus operator and it should have three keys `etcd-ca`, `etcd-client`, `etcd-client-key`.

Right now we ask user to mention the etcd endpoints but this information is already available in terraform state and it can be retrieved from there and fed to component information internally.

Also etcd-client certs are generated on cluster install, using those certs for prometheus is not ideal because they have wide pemissions. So creating a user with limited permissions to read metrics and then creating certs for that user is the ideal way to go forward.
