### ISSUE TITLE
Privileged PSP used by default without extra configurations to allow it

### ISSUE THREAD

**Issue by rata** [kinvolk/lokomotive#426]
I just created a cluster from master (4d3d432c8d21ba87dccb1080d71cadb6f693c00a) and used the created kubeconfig for the following operations

Deploy the following pod (`kubectl apply ...`):
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
  - name: shell
    image: debian
    command: ["sleep", "infinity"]
    securityContext:
      capabilities:
        add:
        - SYS_PTRACE
```

The pod is created:

```
$ kubectl get pods -n default
NAME    READY   STATUS    RESTARTS   AGE
nginx   2/2     Running   0          7s
```

And the PSP is privileged:
```
$ kubectl get pod nginx -o yaml | grep -i psp
    kubernetes.io/psp: zz-privileged
```

IIUC, there is no reason why pods could be created using a privileged PSP in the default namespace and this should be forbidden.

Am I missing something?
