### ISSUE TITLE
Allow user to expose Grafana over ingress

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#456]
Right now there is no way for the user to expose Grafana over ingress. Add knobs to do it, like following:

```yaml
grafana:
  ingress:
    # TODO: Add knob here
    enabled: {{ .ExposeGrafana }}

    annotations:
      kubernetes.io/ingress.class: contour
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: "letsencrypt-production"

    hosts:
    - {{ .IngressHost }}

    tls:
    - hosts:
      - {{ .IngressHost }}
      secretName: {{ .IngressHost }}-tls
```

Add above to https://github.com/kinvolk/lokomotive/blob/9e3eaf64546c2498485a26757be5ae0cc0adf7a2/pkg/components/prometheus-operator/template.go#L49-L57
