### ISSUE TITLE
Allow user to setup Google Oauth for Grafana

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#538]
This can be done in two ways.

## One

One is by providing configs in Prometheus Operator Values file under this section:

```yaml
grafana:
  grafana.ini:
    server:
      domain: monitoring.example.com
    auth.google:
      enabled: true
      client_secret: newS3cretKey
      ...
```

src: https://grafana.com/docs/grafana/v6.5/auth/google/

## Two

Or this can also be replaced with env var as follows:

```bash
export GF_SERVER_DOMAIN=monitoring.example.com
export GF_AUTH_GOOGLE_ENABLED=true
export GF_AUTH_GOOGLE_CLIENT_SECRET=newS3cretKey
```

All the values under `grafana.ini` can be replaced with env var in following format: `GF_<SectionName>_<KeyName>`. 

> Where the section name is the text within the brackets. Everything should be upper case, `.` should be replaced by `_`. As shown above

src: https://grafana.com/docs/grafana/v6.5/installation/configuration/#using-environment-variables
