### ISSUE TITLE
Provide a way for goreleaser to use different GPG key

### ISSUE THREAD

**Issue by surajssd** [kinvolk/lokomotive#912]
Right now goreleaser arbitrarily selects a GPG key to sign the release with. It does not respect the gitconfig.

- There is a way to provide the GPG key using env var. The doc to follow is https://goreleaser.com/ci/actions/#signing.
- Update the release doc after this.

Following config has worked for me in the past:

```yaml
# Enable signing checksums.
signs:
- artifacts: all
  args: ["-u", "11A11111AA111111", "--output", "${signature}", "--detach-sign", "${artifact}"]
```

---

Also the command is changed to 

```
goreleaser release --release-notes <(./scripts/print-version-changelog.sh)
```
